version: '3.8'

services:
  postgres-command-service:
    image: postgres:latest
    container_name: postgres-command-service
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${COMMAND_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${COMMAND_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${COMMAND_SERVICE_DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql-command/data
      - - ./z-docker/initCommandDB.sql:/docker-entrypoint-initdb.d/initCommandDB.sql

    env_file:
      - .env

  postgres-query-service:
    image: postgres:latest
    container_name: postgres-query-service
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${QUERY_SERVICE_DB_USER}
      - POSTGRES_PASSWORD=${QUERY_SERVICE_DB_PASSWORD}
      - POSTGRES_DB=${QUERY_SERVICE_DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql-query/data
      - ./z-docker/initQueryDB.sql:/docker-entrypoint-initdb.d/initQueryDB.sql

    env_file:
      - .env