-- liquibase formatted sql

-- changeset Torchez:1722956619730-1
CREATE SEQUENCE IF NOT EXISTS processed_messages_events_seq START WITH 1 INCREMENT BY 50;

-- changeset Torchez:1722956619730-2
CREATE TABLE processed_messages_events
(
    id                  BIGINT       NOT NULL,
    message_id          VARCHAR(255) NOT NULL,
    entity_id           BIGINT,
    event_type          SMALLINT,
    event_body          VARCHAR(255),
    received_time_stamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_processed_messages_events PRIMARY KEY (id)
);

-- changeset Torchez:1722956619730-3
CREATE TABLE IF NOT EXISTS simple_entity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name   VARCHAR(50),
    email       VARCHAR(255),
    description VARCHAR(1024),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    version     INTEGER                                 NOT NULL,
    CONSTRAINT pk_simpleentity PRIMARY KEY (id)
);

-- changeset Torchez:1722956619730-4
ALTER TABLE processed_messages_events
    ADD CONSTRAINT uc_processed_messages_events_messageid UNIQUE (message_id);

-- changeset Torchez:1722956619730-5
ALTER TABLE simple_entity
    ADD CONSTRAINT uc_simpleentity_email UNIQUE (email);

