-- liquibase formatted sql

-- changeset Torchez:1721909671426-1
CREATE TABLE simple_entity
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name   VARCHAR(50)                             NOT NULL,
    email       VARCHAR(255)                            NOT NULL,
    description VARCHAR(1024),
    CONSTRAINT pk_simpleentity PRIMARY KEY (id)
);

-- changeset Torchez:1721909671426-2
ALTER TABLE simple_entity
    ADD CONSTRAINT uc_simpleentity_email UNIQUE (email);

