server:
  port: 8082

spring:
  application:
    name: query-service

  config:
    import: optional:file:.env[.properties]

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/${QUERY_SERVICE_DB_NAME}
    username: ${QUERY_SERVICE_DB_USER}
    password: ${QUERY_SERVICE_DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096

